// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: http/http_business.proto

package businessServices

import (
	common "github.com/Paukku/ajanvarausjarjestelma/backend/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_http_http_business_proto protoreflect.FileDescriptor

const file_http_http_business_proto_rawDesc = "" +
	"\n" +
	"\x18http/http_business.proto\x12\rhttp_business\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/business.proto2\xae\x02\n" +
	"\x13BusinessCustomerAPI\x12e\n" +
	"\n" +
	"CreateUser\x12\x19.common.CreateUserRequest\x1a\x17.common.GeneralResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/users/createUser\x12]\n" +
	"\bGetUsers\x12\x17.common.GetUsersRequest\x1a\x18.common.GetUsersResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/users/getUsers\x12Q\n" +
	"\vGetUserById\x12\x16.common.GetUserRequest\x1a\f.common.User\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/users/{uuid}B$Z\"/businessServices;businessServicesb\x06proto3"

var file_http_http_business_proto_goTypes = []any{
	(*common.CreateUserRequest)(nil), // 0: common.CreateUserRequest
	(*common.GetUsersRequest)(nil),   // 1: common.GetUsersRequest
	(*common.GetUserRequest)(nil),    // 2: common.GetUserRequest
	(*common.GeneralResponse)(nil),   // 3: common.GeneralResponse
	(*common.GetUsersResponse)(nil),  // 4: common.GetUsersResponse
	(*common.User)(nil),              // 5: common.User
}
var file_http_http_business_proto_depIdxs = []int32{
	0, // 0: http_business.BusinessCustomerAPI.CreateUser:input_type -> common.CreateUserRequest
	1, // 1: http_business.BusinessCustomerAPI.GetUsers:input_type -> common.GetUsersRequest
	2, // 2: http_business.BusinessCustomerAPI.GetUserById:input_type -> common.GetUserRequest
	3, // 3: http_business.BusinessCustomerAPI.CreateUser:output_type -> common.GeneralResponse
	4, // 4: http_business.BusinessCustomerAPI.GetUsers:output_type -> common.GetUsersResponse
	5, // 5: http_business.BusinessCustomerAPI.GetUserById:output_type -> common.User
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_http_business_proto_init() }
func file_http_http_business_proto_init() {
	if File_http_http_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_http_business_proto_rawDesc), len(file_http_http_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_http_business_proto_goTypes,
		DependencyIndexes: file_http_http_business_proto_depIdxs,
	}.Build()
	File_http_http_business_proto = out.File
	file_http_http_business_proto_goTypes = nil
	file_http_http_business_proto_depIdxs = nil
}
